# Generated by Django 5.2.4 on 2025-07-18 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittask',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task_audit_tasks', to='task.task'),
            preserve_default=False,
        ),
    ]
